#!/bin/bash
sudo -S apt-get install -y aptitude

# add ppa   
#sudo add-apt-repository -y ppa:laurent-boulard/openocd
#sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
sudo add-apt-repository -y ppa:pmjdebruijn/ardour-release
sudo add-apt-repository -y ppa:thomas-schiex/blender
sudo add-apt-repository -y ppa:js-reynaud/ppa-kicad
sudo add-apt-repository -y ppa:freecad-maintainers/freecad-stable

sudo -S aptitude update
sudo -S aptitude full-upgrade -y

sudo -S aptitude install -y --with-recommends \
`# terminal tools` \
wine-stable autoconf automake pkg-config gdebi unzip \
`# python` \
python-dev python-pip libpython-dev python3-dev libpython3-dev python-numpy python3-numpy \
checkinstall vim xsel xclip tmux zsh mc htop openvpn \
`# programming` \
make cmake build-essential valgrind ddd doxygen \
clang libclang-dev clang-tools clang-tidy clang-format lldb llvm \
nvidia-cg-toolkit openjdk-8-jdk \
`# libraries` \
libboost-all-dev libgtest-dev libeigen3-dev libflann-dev libtbb-dev \
libpoco-dev libcppunit-dev \
`# version control` \
git gitk mercurial subversion \
`# multimedia` \
vlc \
`# window managers` \
awesome i3 \
`# text editors` \
vim neovim emacs \
`# IDE` \
qtcreator eclipse \
`# microcontrollers` \
openocd binutils-arm-none-eabi gcc-arm-none-eabi \
libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib \
`# scientific computation` \
octave scilab \
`# photo/image editing` \
inkscape gimp \
`# CAD, engineering and modeling` \
kicad ngspice geda freecad blender \
`# DAW, audio` \
ardour audacity 


# Setup git (username, email, etc)
sudo -S aptitude install -y --with-recommends git 
git config --global user.name "Nikolay Bobovnikov"
git config --global user.email nbobovnikov@gmail.com

# cmake - download and install version newer than 3.0 required by rtags
if [ $(dpkg-query -W -f='${Status}' cmake 2>/dev/null | grep -c "install ok installed") -eq 0  ]; then
  echo "No cmake. Setting up cmake."
  rm -fr cmake_tmp && mkdir -p cmake_tmp && cd cmake_tmp && \
  wget --no-clobber  http://www.cmake.org/files/v3.7/cmake-3.7.0-rc1.tar.gz && \
  tar -xf cmake*.tar.gz && cd cmake* && \
  ./bootstrap && make && sudo checkinstall --default --pkgname=cmake --pkgversion=3.7.0 && \
  sudo dpkg -i cmake*.deb && \
  cd ../../../ && rm -fr cmake_tmp
fi

# rtags
if [ $(dpkg-query -W -f='${Status}' rtags 2>/dev/null | grep -c "install ok installed") -eq 0  ]; then
  echo "No rtags. Setting up rtags."
  rm -fr rtags_tmp && mkdir -p rtags_tmp && cd rtags_tmp && \
  git clone --recursive https://github.com/Andersbakken/rtags.git && \
  cd rtags && mkdir build && cd build && \
  cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .. && make && \
  sudo -S checkinstall --install=yes --default --pkgname=rtags && \
  sudo -S dpkg -i rtags*.deb && \
  cd ../../ && rm -fr rtags && cd .. && rm -fr rtags_tmp
fi

